// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCouei3DmvEatwhBdJAZCyJS65yLE_zA0A',
    appId: '1:825512861147:web:9336f0b37e49c9c123dbfe',
    messagingSenderId: '825512861147',
    projectId: 'wargabut-11',
    authDomain: 'wargabut-11.firebaseapp.com',
    storageBucket: 'wargabut-11.appspot.com',
    measurementId: 'G-KQMQ2FE7YE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6AdPjHPDD-h-YoKn35HWuIJPsGGYu6EY',
    appId: '1:825512861147:android:5402a73d4b8ed41823dbfe',
    messagingSenderId: '825512861147',
    projectId: 'wargabut-11',
    storageBucket: 'wargabut-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84hROJODzj0F-uPVTW4DB6-4OZmbpRKA',
    appId: '1:825512861147:ios:fcd51bce16b3f4a423dbfe',
    messagingSenderId: '825512861147',
    projectId: 'wargabut-11',
    storageBucket: 'wargabut-11.appspot.com',
    iosBundleId: 'com.example.wargabut',
  );
}
